name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Build and deploy
        run: |
          cp README.md docs/list.md
          pip install -r requirements.txt
          mkdocs build
          mkdocs gh-deploy --force
