name: Links validator

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # At 09:00 on Monday: https://crontab.guru/#0_9_*_*_1
    - cron: "0 9 30 * 0"

jobs:
  link_checker:
    name: Link Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check links
        uses: lycheeverse/lychee-action@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose --no-progress --timeout 10 --max-concurrency 2 --exclude 'twitter.com' -- './**/*.md'
          output: ./lychee/out.md

      - name: Get current date
        id: date
        run: echo "::set-output name=now::$(date +'%d-%m-%Y')"

      - name: Create issue when fail
        if: ${{ steps.lychee.outputs.exit_code }} != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Automated Links Checker Report for ${{ steps.date.outputs.now }}
          content-filepath: ./lychee/out.md
          labels: links validator
