apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        # This image will be updated by the CI/CD pipeline
        image: your-dockerhub-username/python-app:latest
        ports:
        - containerPort: 5000
