name: Test Docker Login

on:
  workflow_dispatch:

jobs:
  login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}