name: Test Google Cloud Authentication

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auth_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test Google Cloud Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Check Auth Status
        run: |
          echo "Authentication successful!"
          echo "Your project ID is: ${{ secrets.GCP_PROJECT_ID }}"
